spring.application.name=appliweb
server.port=${PORT:8080}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

format.date=dd/MM/yyyy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
