name: Affichage fichiers

on:
  workflow_dispatch:

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Vérifier les fichiers
        run: ls -la