name: Dire Bonjour

on:
  push:
    branches:
      - main

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest

    steps:
    - name: Afficher Bonjour
      run: echo "Bonjour depuis GitHub Actions !"

    - name: Lister les fichiers
      run: ls -al