name: Configurer Java 21

on:
  # manuel
  workflow_dispatch:

jobs:
  configurer: #identifiant du job
    runs-on: ubuntu-latest # runner obligatoire
    steps: # les étapes obligatoires
    - name: Configurer java 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: 'temurin'
        maven: 'cache'

    - name: Afficher les versions des outils
      run: |
        echo 'Version de java:'
        java -version
        echo 'Version de maven:'
        mvn -v

    - name: Récupérer le code applicatif
      uses: actions/checkout@v5

    - name: Afficher les fichiers source à la racine
      run: ls -al

