name: Dire Bonjour

on:
  workflow_dispatch

env:
  SPRING_PROFILE: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher Bonjour
        run: echo "Job de build démarré"

  deploy:
    # Deploy ne s'exécute que sur la branche main dans un contexte de production
    if: github.ref == 'refs/head/main' && env.SPRING_PROFILE == 'prod'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name : Action quelconque
        run : echo "Job de test démarré"