name: CI Java avec Maven
run-name: Build Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
    - name: Récupérer le code source
      uses: actions/checkout@v4

    - name: Configurer JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Construire avec Maven
      run: mvn -B clean verify -Dspring.profiles.active=test

    - name: Sauvegarder le rapport JaCoCo
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco

    - name: Initialiser CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java-kotlin

    - name: Analyser avec CodeQL
      uses: github/codeql-action/analyze@v4

    - name: Sauvegarder les artifacts
      uses: actions/upload-artifact@v4
      with:
        name: java-artifact
        path: target/*.jar