name: CI/CD projet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      security-events: write # pour la mise à jour de l'onglet Security and quality
      contents: read # lire le code source

    steps:
    # Mettre les steps checkout et setup-java
    - name: Récupérer le code source
      uses: actions/checkout@v4

    - name: Configurer JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Initialiser CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: java-kotlin

    - name: Construire avec Maven
      run: mvn -B clean verify -Dspring.profiles.active=test

    - name: Analyser avec CodeQL
      uses: github/codeql-action/analyze@v4

    - name: Sauvegarder le rapport JaCoCo
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report # nom donné au rapport au niveau du build
        path: target/site/jacoco # endroit où est généré le rapport Java sur le runner

